stages:
  - build

build-debug:
    stage: build
    tags:
      - rust
    script:
      - cargo build --verbose

build-release:
    stage: build
    tags:
      - rust
    script:
      - cargo build --release --verbose

