image: storedbox/rust:nightly

stages:
  - build

debug build:
    stage: build
    script:
      - cargo build --verbose

release build:
    stage: build
    script:
      - cargo build --release --verbose
