image: storedbox/rust:nightly

stages:
  - build

build-debug:
    stage: build
    tags:
      - docker
    script:
      - cargo build --verbose

build-release:
    stage: build
    tags:
      - docker
    script:
      - cargo build --release --verbose

