image: storedbox/rust:nightly

stages:
- build

Debug Build:
  stage: build
  tags:
  - docker
  script:
  - cargo build --verbose

Release Build:
  stage: build
  tags:
  - docker
  script:
  - cargo build --verbose --release
